version: '3'
services:
  codeeducation:
    container_name: codeeducation
    build: .
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3030:3000"
    environment:
      TEXT: Code.education Rocks!
