FROM golang:1.8-alpine AS builder

WORKDIR /go/src/app
ADD ./src /go/src/app

RUN go build -o main .

##
  
FROM scratch
COPY --from=builder /go/src/app/main /app/main

WORKDIR /go/src/app
CMD ["/app/main"]